[versions]
composeCompiler = "1.4.3"

[libraries]
coreKtx = "androidx.core:core-ktx:1.9.0"
lifecycleKit = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.2"
composeBom = "androidx.compose:compose-bom:2023.03.00"
composeActivity = "androidx.activity:activity-compose:1.8.0"
composeUi = { module = "androidx.compose.ui:ui" }
composePreview = { module = "androidx.compose.ui:ui-tooling-preview" }
composeMaterial = "com.google.android.material:material:1.11.0-beta01"
composeMaterial3 = { module = "androidx.compose.material3:material3" }
